name: 18 - 1 - Reusable Wrokflows - Reusable Definition
on:
  workflow_call:
    inputs:
      target-directory:
        required: true
        type: string
    outputs:
      build-status:
        description: The status of the build process
        value: ${{ jobs.deploy.outputs.build-status }}
      url:
        description: The url of the deployed version
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build_status }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v5
      - name: print
        run: ls -lr
      - name: Build
        id: build
        run: |
          echo "Building using directory ${{ inputs.target-directory }}"
          echo "build-status=success" >> "$GITHUB_OUTPUT"
      - name: Deploy
        id: deploy
        run: |
          echo "Deploying using artifacts"
          echo "url=https://google.com" >> "$GITHUB_OUTPUT"
