name: 19 - 1 - Managing Concurrency
on: workflow_dispatch
concurrency:
  group: <retrieve the workflow name here>-<retrieve the git ref here>
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Ping URL
        uses: ./github/actions/docker-ping-url
        with:
          url: https://gooooooooogle.com
          max_trials: 20
          deplay: 5
